### ISSUE TITLE
Error in the Style

### ISSUE THREAD

**Issue by emersondivB0** [ttntm/astro-landing-page#5]
I've been trying to deploy the project, but everytime it loads without style, like just html, I don't change anything, just pure deploy (in Vercel) 
![landing-1](https://github.com/ttntm/astro-landing-page/assets/116042932/2951560d-323d-4692-9c16-ff39f69c609c)

**Comment by ttntm** [comment]
hi @emersondivB0,

this is in fact "working as intended" as per Astro's configuration requirement of setting the final, deployed URL in the configuration file - see https://docs.astro.build/en/reference/configuration-reference/#site

I revised the config file to make it a little more obvious and I've also updated the readme accordingly in https://github.com/ttntm/astro-landing-page/commit/c34fb1ac2d3378dfd3f7597dd116566313e45f2b

Setting up a new site and entering it's URL will lead to a working site:

![Screenshot from 2024-03-31 18-00-28](https://github.com/ttntm/astro-landing-page/assets/41571384/e9f0d880-26bb-43c4-9b86-e82bbd8684db)

=> https://jazzy-torrone-98b697.netlify.app/

**Comment by emersondivB0** [comment]
Thank you very much bro, I now understand, have a great day!
